# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajax_test.Musician')),
            ],
        ),
    ]
