# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicians',
            name='musician',
        ),
        migrations.DeleteModel(
            name='Musicians',
        ),
    ]
