# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 23:09
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'IMMEDIATELY'), (1, 'SOON'), (2, 'LATER'), (3, 'INACTIVE')], default=0)),
                ('purchased', models.BooleanField(default=False)),
                ('estimated_number_of_days', models.PositiveSmallIntegerField(default=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('consumed_date', models.DateTimeField(blank=True, null=True)),
                ('predicted_replace_days', models.PositiveSmallIntegerField(blank=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('product_image', models.URLField()),
                ('barcode', models.CharField(blank=True, max_length=32, validators=[django.core.validators.MaxLengthValidator(32)])),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='thing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Thing'),
        ),
    ]
