# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MaxValueValidator(255)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=32, validators=[django.core.validators.MaxValueValidator(32)])),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(255)])),
                ('number_in_household', models.PositiveSmallIntegerField(default=1)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now=True)),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.People')),
            ],
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MaxValueValidator(255)])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('product_image', models.URLField()),
                ('upc', models.CharField(blank=True, max_length=32, validators=[django.core.validators.MaxValueValidator(32)])),
            ],
        ),
        migrations.CreateModel(
            name='UsageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_date', models.DateTimeField(auto_now=True)),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.People')),
                ('thing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Things')),
            ],
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='thing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Things'),
        ),
    ]
